[project]
name = "lace-dock"
version = "0.5.25"
description = "Advanced PySide6 docking system"
authors = [
    {name = "opticsWolf", email = "opticswolf@protonmail.com"}
]
license = {text = "Apache-2.0"}
requires-python = ">=3.10"
dependencies = [
    "pyside6",
    "PySideSix-Frameless-Window",
    "pydantic>=2.0",
]
readme = "README.md"

classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: User Interfaces",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Homepage = "https://github.com/opticsWolf/Lace"
Documentation = "https://github.com/opticsWolf/Lace#readme"
Repository = "https://github.com/opticsWolf/Lace"
Issues = "https://github.com/opticsWolf/Lace/issues"
Changelog = "https://github.com/opticsWolf/Lace/releases"

[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["lace"]
include-package-data = true

# Include non-Python assets (SVG icons, etc.)
[tool.setuptools.package-data]
lace = [
    "resources/lace_icons/*.svg",
]
