#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Emit `src/schema_generated.rs` from the `dock_theme` style schemas.

Introspects `_SCHEMA_MAP` (field names in declaration order plus their
defaults) so the ghost-token contract — engine output keys must be declared
schema fields — is checked against the real schemas, not a copy.

Usage (from repo root):
    .venv/Scripts/python.exe rust/lace-core/codegen/emit_schema.py
"""

import dataclasses
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))

from lace.dock_style_manager import _SCHEMA_MAP  # noqa: E402
from lace.dock_theme import DockStyleCategory  # noqa: E402

OUT = REPO / "rust" / "lace-core" / "src" / "schema_generated.rs"

ORDER = [
    DockStyleCategory.CORE, DockStyleCategory.PANEL, DockStyleCategory.TAB,
    DockStyleCategory.TITLE_BAR, DockStyleCategory.SIDEBAR,
    DockStyleCategory.SIDEPANEL, DockStyleCategory.SPLITTER,
    DockStyleCategory.OVERLAY,
]
assert set(ORDER) == set(_SCHEMA_MAP) == set(DockStyleCategory)


def rust_default(value):
    """A schema default as a `ThemeValue` expression, or None for unset."""
    if value is None:
        return None
    if isinstance(value, bool):
        return "ThemeValue::Bool(true)" if value else "ThemeValue::Bool(false)"
    if isinstance(value, int):
        return f"ThemeValue::Num(Num::Int({value}))"
    if isinstance(value, float):
        return f"ThemeValue::Num(Num::Float({value!r}))"
    if isinstance(value, str):
        assert '"' not in value, value
        return f'ThemeValue::Str("{value}".to_string())'
    if isinstance(value, (list, tuple)):
        assert all(isinstance(v, (int, float)) and not isinstance(v, bool)
                   for v in value), f"unexpected default list: {value!r}"
        items = ", ".join(
            f"Num::Int({v})" if isinstance(v, int) else f"Num::Float({v!r})"
            for v in value)
        return f"ThemeValue::NumList(vec![{items}])"
    raise TypeError(f"unexpected schema default: {value!r}")


def main() -> None:
    field_arms = []
    default_arms = []
    for cat in ORDER:
        schema = _SCHEMA_MAP[cat]
        names = [f.name for f in dataclasses.fields(schema)]
        field_arms.append(
            f'        StyleCategory::{cat.name.title().replace("_", "")}'
            f' => &[{", ".join(chr(34) + n + chr(34) for n in names)}],'
        )
        for f in dataclasses.fields(schema):
            default = schema.__dataclass_fields__[f.name].default
            expr = rust_default(default)
            if expr is None:
                continue
            default_arms.append(
                f'        (StyleCategory::{cat.name.title().replace("_", "")},'
                f' "{f.name}") => Some({expr}),'
            )
    # StyleCategory variant names: Core, Panel, Tab, TitleBar, Sidebar,
    # SidePanel, Splitter, Overlay.
    body = "\n".join(field_arms).replace("Titlebar", "TitleBar").replace(
        "Sidepanel", "SidePanel")
    defaults = "\n".join(default_arms).replace("Titlebar", "TitleBar").replace(
        "Sidepanel", "SidePanel")
    OUT.write_text(
        "//! GENERATED by `codegen/emit_schema.py` — do not edit.\n"
        "//! Declared tokens and defaults of the eight style schemas in\n"
        "//! `lace/dock_theme.py`, for the ghost-token contract and the\n"
        "//! Phase-6 style manager.\n\n"
        "use super::theme::{StyleCategory, ThemeValue};\n"
        "#[allow(dead_code)]\n"
        "use super::theme::Num;\n\n"
        "/// Declared field names of one category schema, in declaration order.\n"
        "pub fn schema_fields(category: StyleCategory) -> &'static [&'static str] {\n"
        "    match category {\n"
        f"{body}\n"
        "    }\n"
        "}\n\n"
        "/// Default value of one declared token; `None` means unset (a colour\n"
        "/// awaiting the theme, or an optional token).\n"
        "#[allow(dead_code)]\n"
        "pub fn schema_default(category: StyleCategory, token: &str) -> Option<ThemeValue> {\n"
        "    match (category, token) {\n"
        f"{defaults}\n"
        "        _ => None,\n"
        "    }\n"
        "}\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
