#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Emit `src/svg_colors_generated.rs` from Qt's named-colour table.

`ThemeJson` accepts SVG colour names (resolved through `QColor` on the Python
side), so the Rust loader needs the same table. Generated from
`QColor.colorNames()` itself — no hand-copied list to rot.

Usage (from repo root):
    .venv/Scripts/python.exe rust/lace-core/codegen/emit_svg_colors.py
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO))

from PySide6.QtGui import QColor  # noqa: E402

OUT = REPO / "rust" / "lace-core" / "src" / "svg_colors_generated.rs"


def main() -> None:
    rows = []
    for name in QColor.colorNames():
        c = QColor(name)
        assert c.isValid(), name
        r, g, b, a = c.getRgb()
        rows.append((name, r, g, b, a))
    rows.sort()
    assert len(rows) > 100, f"suspiciously few colour names: {len(rows)}"
    arms = "\n".join(
        f'    ("{name}", Rgba::new({r}, {g}, {b}, {a})),'
        for name, r, g, b, a in rows
    )
    OUT.write_text(
        "//! GENERATED by `codegen/emit_svg_colors.py` — do not edit.\n"
        "//! Qt's SVG colour-keyword table (`QColor.colorNames()`), sorted for\n"
        "//! binary search. Lookup is case-insensitive, like `QColor`.\n\n"
        "use super::theme::Rgba;\n\n"
        "const SVG_COLORS: &[(&str, Rgba)] = &[\n"
        f"{arms}\n"
        "];\n\n"
        "/// Resolve an SVG colour keyword (case-insensitive), or `None`.\n"
        "pub fn svg_color(name: &str) -> Option<Rgba> {\n"
        "    let lowered = name.to_lowercase();\n"
        "    SVG_COLORS\n"
        "        .binary_search_by(|(key, _)| key.cmp(&lowered.as_str()))\n"
        "        .ok()\n"
        "        .map(|index| SVG_COLORS[index].1)\n"
        "}\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(rows)} names)")


if __name__ == "__main__":
    main()
